### ISSUE TITLE
better dict validation

### ISSUE THREAD

**Issue by trehn** [bundlewrap/bundlewrap#120]
use voluptuous to validate item, node, and group dicts

**Comment by MaZderMind** [comment]
Maybe a related issue is validating the list of bundles mentioned in a node. Referencing a missing bundle results in a pretty meaningless error message:
````
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/__init__.py", line 66, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/__init__.py", line 155, in main
    for line in output:
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/apply.py", line 80, in bw_apply
    worker_pool.run()
  File "/Library/Python/2.7/site-packages/bundlewrap/concurrency.py", line 150, in run
    traceback = "".join(format_tb(exc.__traceback__))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 95, in extract_tb
    f = tb.tb_frame
AttributeError: 'list' object has no attribute 'tb_frame'
````

**Comment by trehn** [comment]
@MaZderMind Hmm, that's actually a general problem with exception reporting in Python 2... which I thought I had fixed in 2.8.0... will look into it

**Comment by trehn** [comment]
@MaZderMind Can't reproduce, message should be "NoSuchBundle: Node 'foo' wants bundle 'foo', but it doesn't exist."

Which version of bw are you using?

**Comment by MaZderMind** [comment]
@trehn 2.7.1, so it's a problem on my side. sorry for hijacking this thread.
