### ISSUE TITLE
AttributeError: 'BundleItem' object has no attribute 'node'

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#216]
Might be related to #162 

    Traceback (most recent call last):
      File "/home/meh/git/bundlewrap/bundlewrap/concurrency.py", line 48, in _worker_process
        return_value = target(*msg['args'], **msg['kwargs'])
      File "/home/meh/git/bundlewrap/bundlewrap/node.py", line 581, in test
        workers=workers,
      File "/home/meh/git/bundlewrap/bundlewrap/node.py", line 715, in test_items
        task_id=item.node.name + ":" + item.bundle.name + ":" + item.id,
    AttributeError: 'BundleItem' object has no attribute 'node'

**Comment by trehn** [comment]
Yeah, it probably is. Will take a look.

**Comment by trehn** [comment]
Fixed. No idea how I missed that.
