### ISSUE TITLE
TypeError: metadata key for node1 at path 'interfaces' is not a string

### ISSUE THREAD

**Issue by unclesamwk** [bundlewrap/bundlewrap#407]
Hey,

i use the example for metadata ...

Working with node metadata

Quite often you will attach custom metadata to your nodes in nodes.py, e.g.:
```
nodes = {
    "node1": {
        "metadata": {
            "interfaces": {
                "eth0": "10.1.1.47",
                "eth1": "10.1.2.47",
            },
        },
    },
}
```
Test:
```
root@HP-ProBook-640-G1: ~ > bw test
✓ all  has no subgroup loops
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bundlewrap/cmdline/__init__.py", line 68, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bundlewrap/cmdline/__init__.py", line 153, in main
    pargs.func(repo, text_pargs)
  File "/usr/lib/python2.7/dist-packages/bundlewrap/cmdline/test.py", line 341, in bw_test
    test_metadata_keys(node)
  File "/usr/lib/python2.7/dist-packages/bundlewrap/cmdline/test.py", line 108, in test_metadata_keys
    check_metadata_keys(node)
  File "/usr/lib/python2.7/dist-packages/bundlewrap/metadata.py", line 92, in check_metadata_keys
    path="'->'".join(path[:-1]),
TypeError: metadata key for node1 at path 'interfaces' is not a string
```
```
root@HP-ProBook-640-G1: ~ > bw --version
3.2.1
```
You have any idea?

greetings sam

**Comment by unclesamwk** [comment]
With latest version it works.
