### ISSUE TITLE
invalid name for k8s_clusterrole

### ISSUE THREAD

**Issue by kllex** [bundlewrap/bundlewrap#429]
Hi,
I just encountered a problem while trying to roll out the current cert-manager bundle into a kubernetes cluster via bundlewrap:

```
$ bw apply -i myk8scluster
Traceback (most recent call last):
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/cmdline/__init__.py", line 68, in wrapper
    return f(*args, **kwargs)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/cmdline/__init__.py", line 153, in main
    pargs.func(repo, text_pargs)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/cmdline/apply.py", line 34, in bw_apply
    io.progress_set_total(count_items(pending_nodes))
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/utils/cmdline.py", line 16, in count_items
    count += len(node.items)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/utils/__init__.py", line 47, in cache_wrapper
    return_value = tuple(return_value)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/node.py", line 538, in items
    for item in bundle.items:
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/utils/__init__.py", line 47, in cache_wrapper
    return_value = tuple(return_value)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/bundle.py", line 74, in items
    item_attrs,
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/bundle.py", line 80, in make_item
    return item_class(self, item_name, item_attrs)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/items/kubernetes.py", line 46, in __init__
    super(KubernetesItem, self).__init__(*args, **kwargs)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/items/__init__.py", line 148, in __init__
    self._validate_name(bundle, name)
  File "/home/kllex/.local/lib/python3.7/site-packages/bundlewrap/items/__init__.py", line 401, in _validate_name
    type=cls.ITEM_TYPE_NAME,
bundlewrap.exceptions.BundleError: invalid name for k8s_clusterrole in bundle 'certmanager': cert-manager-webhook:webhook-requester (must not contain colon)
```

It seems that trying to roll out clusterroles with a colon in the name is forbidden. I am not aware of any restrictions on the kubernetes side regarding colons in object names (and it is heavily used in current kubernetes setups by default, especially in the *clusterroles* and *clusterrolebindings*).

So I was wondering:
a) why this restriction is necessary in bundlewrap
b) how to fix this problem as it seems unfeasible to fix every upstream software.

best regards

**Comment by trehn** [comment]
Item names may not have to colons to avoid mixups with canned actions.
Just choose a different item name. You do not have to name the bw item exactly the same as the resource in k8s. Choose a colon-less name for the item and set the real name (with colon) in your manifest.
