### ISSUE TITLE
Better error message when metadata reactors don’t return anything

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#753]
I just had a mild case of the stupid. I defined a reactor and forgot the final `return` statement. bw just told me this:
```
$ bw test my-node
Traceback (most recent call last):
  File "/home/username/git/bundlewrap/bundlewrap/utils/cmdline.py", line 71, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/username/git/bundlewrap/bundlewrap/cmdline/__init__.py", line 77, in main
    pargs.func(repo, text_pargs)
  File "/home/username/git/bundlewrap/bundlewrap/cmdline/test.py", line 281, in bw_test
    test_reactor_provides(repo, nodes, args['quiet'])
  File "/home/username/git/bundlewrap/bundlewrap/cmdline/test.py", line 240, in test_reactor_provides
    node.metadata.get(())
  File "/home/username/git/bundlewrap/bundlewrap/metagen.py", line 189, in get
    self._metagen._build_node_metadata(self._node)
  File "/home/username/git/bundlewrap/bundlewrap/metagen.py", line 258, in _build_node_metadata
    reactors_run, only_keyerrors = self.__run_reactors()
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/git/bundlewrap/bundlewrap/metagen.py", line 396, in __run_reactors
    self.__run_reactor(
  File "/home/username/git/bundlewrap/bundlewrap/metagen.py", line 470, in __run_reactor
    extra_paths = extra_paths_in_dict(new_metadata, reactor._provides)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/git/bundlewrap/bundlewrap/utils/dicts.py", line 251, in extra_paths_in_dict
    for actual_path in map_dict_keys(dict_obj, leaves_only=True):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/git/bundlewrap/bundlewrap/utils/dicts.py", line 229, in map_dict_keys
    for key, value in dict_obj.items():
                      ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```
We could easily add a check after calling reactors: If they return `None`, then it’s a user error and we can tell the user which reactor is responsible.

**Comment by vain** [comment]
Also, this stack trace does *not* show up for `bw metadata`, only other commands like `bw test`. Quite confusing. (I assume there’s only one place where reactors are called, so this would be fixed implicitly by adding a check for returning `None`.)
