### ISSUE TITLE
Concurrency blockers can create dependency loops

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#779]
Consider this `items.py`:

```python
pkg_pip['pip-foo'] = {'needs': {'pkg_apt:apt-foo'}}
pkg_pip['pip-baz'] = {}

pkg_apt['apt-foo'] = {}
pkg_apt['apt-baz'] = {'needs': {'pkg_pip:pip-baz'}}
```
*Sometimes*, it throws this error:
```
$ bw test node-1
✓ No reactors violated their declared keys
✓ node-1  has no metadata conflicts
Traceback (most recent call last):
  File "/home/phofmann/git/bundlewrap/bundlewrap/utils/cmdline.py", line 71, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/phofmann/git/bundlewrap/bundlewrap/cmdline/__init__.py", line 77, in main
    pargs.func(repo, text_pargs)
  File "/home/phofmann/git/bundlewrap/bundlewrap/cmdline/test.py", line 302, in bw_test
    test_items(nodes, args['ignore_missing_faults'], args['quiet'])
  File "/home/phofmann/git/bundlewrap/bundlewrap/cmdline/test.py", line 69, in test_items
    raise ItemDependencyLoop(item_queue.items_with_deps)
bundlewrap.deps.ItemDependencyLoop: There was a dependency problem on node 'node-1'. Look at the debug.svg generated by the following command and try to find a loop:


printf 'digraph bundlewrap\n{\nrankdir = LR\ngraph [color="#303030"; fontname=Helvetica; penwidth=2; shape=box; style="rounded,dashed"]\nnode [color="#303030"; fillcolor="#303030"; fontcolor=white; fontname=Helvetica; shape=box; style="rounded,filled"]\nedge [arrowhead=vee]\nsubgraph cluster_0\n{\nlabel = "a"\n"pkg_apt:apt-baz"\n"pkg_pip:pip-foo"\n"pkg_pip:pip-baz"\n"pkg_apt:apt-foo"\n}\n"pkg_apt:apt-baz" -> "pkg_pip:pip-baz" [color="#C24948",penwidth=2]\n"pkg_apt:apt-foo" -> "pkg_apt:apt-baz" [color="#714D99",penwidth=2]\n"pkg_pip:pip-baz" -> "pkg_pip:pip-foo" [color="#714D99",penwidth=2]\n"pkg_pip:pip-foo" -> "pkg_apt:apt-foo" [color="#C24948",penwidth=2]\nfontsize = 28\nlabel = "node-1"\nlabelloc = "t"\n}' | dot -Tsvg -odebug.svg



Additionally, here is a list of all items involved and their remaining dependencies:

pkg_apt:apt-baz	pkg_pip:pip-baz
pkg_pip:pip-foo	pkg_apt:apt-foo
pkg_pip:pip-baz	pkg_pip:pip-foo
pkg_apt:apt-foo	pkg_apt:apt-baz
```

Note the purple concurrency blockers:

![debug](https://github.com/user-attachments/assets/a6d572d8-d30c-433c-a4e4-d0eadc16b0b4)

**Comment by vain** [comment]
When you’re lucky, you get this instead:

![debug](https://github.com/user-attachments/assets/c3fb3a96-2dee-4e97-b257-95fe03533ef0)
